"""Crear tabla detalle_venta

Revision ID: 0251fd08bf99
Revises: 3ea9be2165ce
Create Date: 2025-05-07 15:25:49.194219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0251fd08bf99'
down_revision = '3ea9be2165ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_venta',
    sa.Column('detalle_venta_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.venta_id'], ),
    sa.PrimaryKeyConstraint('detalle_venta_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_venta')
    # ### end Alembic commands ###
